/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ===== 主色系（活力蓝紫 + 珊瑚橙） =====
        primary: {
          DEFAULT: '#6366F1',
          light: 'rgba(99, 102, 241, 0.12)',
          'light-2': 'rgba(99, 102, 241, 0.2)',
          dark: '#FF7A59',
          hover: 'rgba(99, 102, 241, 0.5)',
          muted: 'rgba(99, 102, 241, 0.8)',
        },
        // ===== 链接色 =====
        link: {
          DEFAULT: '#1890ff',
          hover: '#40a9ff',
        },
        // ===== 状态色 =====
        success: {
          DEFAULT: '#52c41a',
          light: '#4caf50',
          bg: '#d4edda',
          text: '#155724',
          border: '#c3e6cb',
        },
        error: {
          DEFAULT: '#ff4d4f',
          light: '#f44336',
          bg: '#f8d7da',
          text: '#721c24',
          border: '#f5c6cb',
          'btn-bg': 'rgba(255, 27, 27, 0.403)',
          'btn-border': 'rgba(255, 113, 113, 0.455)',
          'btn-shadow': 'rgb(255, 81, 81)',
        },
        warning: {
          DEFAULT: '#ff9800',
          bg: '#fff3cd',
          text: '#856404',
          border: '#ffeeba',
        },
        info: {
          bg: '#d1ecf1',
          text: '#0c5460',
          border: '#bee5eb',
        },
        // ===== 平台色 =====
        platform: {
          qq: '#31c27c',
          'qq-dark': '#1db954',
          netease: '#c20c0c',
          'netease-dark': '#e63946',
          vip: '#faad14',
          'vip-bg': '#fff7e6',
          'vip-border': '#ffd591',
          'vip-gradient-end': '#ff6a00',
          green: '#23a30d',
          'qq-mid': '#1db954',
        },
        // ===== 中性色（文字） - 支持深色模式 =====
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          quaternary: 'var(--color-text-quaternary)',
          muted: 'var(--color-text-muted)',
          dark: 'var(--color-text-dark)',
          'blue-dark': 'var(--color-text-blue-dark)',
          'blue-deep': 'var(--color-text-blue-deep)',
          'blue-muted': 'var(--color-text-blue-muted)',
          'blue-sub': 'var(--color-text-blue-sub)',
          'blue-placeholder': 'var(--color-text-blue-placeholder)',
          'blue-label': 'var(--color-text-blue-label)',
          'medium': 'var(--color-text-medium)',
          'blue-gray': 'var(--color-text-blue-gray)',
          'warning': 'var(--color-text-warning)',
        },
        // ===== 中性色（背景） - 支持深色模式 =====
        surface: {
          DEFAULT: 'var(--color-surface)',
          soft: 'var(--color-surface-soft)',
          muted: 'var(--color-surface-muted)',
          card: 'var(--color-surface-card)',
          elevated: 'var(--color-surface-elevated)',
          'elevated-hover': 'var(--color-surface-elevated-hover)',
          'gray-light': 'var(--color-surface-gray-light)',
          gray: 'var(--color-surface-gray)',
          'gray-hover': 'var(--color-surface-gray-hover)',
          'blue-light': 'var(--color-surface-blue-light)',
          'blue-soft': 'var(--color-surface-blue-soft)',
          'blue-pale': 'var(--color-surface-blue-pale)',
          'blue-pick': 'var(--color-surface-blue-pick)',
          'blue-hover': 'var(--color-surface-blue-hover)',
          'green-light': 'var(--color-surface-green-light)',
          'red-light': 'var(--color-surface-red-light)',
          'yellow-light': 'var(--color-surface-yellow-light)',
          'header': 'var(--color-surface-header)',
        },
        // ===== 中性色（边框） - 支持深色模式 =====
        border: {
          DEFAULT: 'var(--color-border)',
          light: 'var(--color-border-light)',
          'lighter': 'var(--color-border-lighter)',
          'blue-light': 'var(--color-border-blue-light)',
          'blue-soft': 'var(--color-border-blue-soft)',
          'blue-muted': 'var(--color-border-blue-muted)',
          'blue-pale': 'var(--color-border-blue-pale)',
          'blue-page': 'var(--color-border-blue-page)',
          'blue-input': 'var(--color-border-blue-input)',
          'blue-source': 'var(--color-border-blue-source)',
          'blue-expand': 'var(--color-border-blue-expand)',
          green: '#31c27c',
          red: '#ff4d4f',
          platform: 'var(--color-border-platform)',
          'platform-hover': 'var(--color-border-platform-hover)',
          'dashed': 'var(--color-border-dashed)',
          'pink': 'var(--color-border-pink)',
          'orange': '#ffd591',
        },
        // ===== 特殊色 =====
        delete: '#ff6b6b',
        'input-bg': 'rgba(118, 118, 118, 0.563)',
        'input-border': 'rgba(199, 199, 199, 0.455)',
        'input-focus-bg': 'rgba(176, 176, 176, 0.563)',
        'register-bg': 'rgba(0, 132, 255, 0.35)',
        'register-border': 'rgba(105, 187, 255, 0.5)',
        'register-shadow': 'rgba(105, 187, 255, 0.8)',
      },
      fontFamily: {
        myfont: ['MyFont', 'sans-serif'],
        myfont2: ['MyFont2', 'sans-serif'],
        mcfont: ['MCFont', 'sans-serif'],
      },
      boxShadow: {
        'glass': '0 4px 80px rgba(139, 139, 139, 0.2)',
        'header': '0px 5px 15px rgba(94, 93, 93, 0.5)',
        'card': '0 10px 30px rgba(0, 0, 0, 0.12)',
        'card-lg': '0 10px 30px rgba(0, 0, 0, 0.16)',
        'panel': '0 8px 32px rgba(0, 0, 0, 0.08)',
        'dialog': '0 20px 50px rgba(0, 0, 0, 0.25)',
        'dialog-lg': '0 20px 60px rgba(0, 0, 0, 0.3)',
        'drawer': '-8px 0 30px rgba(0, 0, 0, 0.1)',
        'cover': '0 8px 30px rgba(0, 0, 0, 0.3)',
        'hover': '0 8px 24px rgba(0, 0, 0, 0.1)',
        'hover-card': '0 4px 12px rgba(0, 0, 0, 0.1)',
        'input': '0 4px 80px rgba(201, 200, 200, 0.5)',
        'focus-red': '0 0 20px rgb(255, 81, 81)',
        'focus-blue': '0 0 20px rgba(105, 187, 255, 0.8)',
        'green-sm': '0 0 6px rgba(82, 196, 26, 0.5)',
        'green-md': '0 4px 12px rgba(49, 194, 124, 0.2)',
        'green-lg': '0 6px 20px rgba(49, 194, 124, 0.4)',
        'red-lg': '0 6px 20px rgba(194, 12, 12, 0.4)',
        'active-white': '0 0 10px rgba(255, 255, 255, 0.2)',
        'active-green': '0 4px 12px rgba(49, 194, 124, 0.4)',
      },
      backgroundImage: {
        'gradient-primary': 'none',
        'gradient-primary-h': 'none',
        'gradient-qq': 'none',
        'gradient-netease': 'none',
        'gradient-vip': 'none',
        'gradient-cover': 'none',
      },
    },
  },
  plugins: [],
}
