services:
  frontend:
    build:
      context: ./frontend
    image: juzixiaoren/togemusic-react:frontend-v4 # 您的前端镜像名
    ports:
      - "14514:14514"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: juzixiaoren/togemusic-react:backend-v4 # 您的后端镜像名
    ports:
      - "8034:8034"
    depends_on:
      - redis
    volumes:
      - ./data/db:/backend/dao/db
      - ./data/uploads:/backend/server/uploads
    environment:
      - CORS_ORIGINS=*
      - SOCKET_PATH=/socket.io
      - PYTHONUNBUFFERED=1
      - SOCKETIO_ASYNC_MODE=gevent
      - SOCKETIO_MESSAGE_QUEUE=redis://redis:6379/0
      - GUNICORN_WORKERS=1
      - QQMUSIC_COOKIE=${QQMUSIC_COOKIE:-}

  redis:
    image: redis:7-alpine
    restart: unless-stopped
